name: retailpulse
version: '1.0.0'
config-version: 2

profile: retailpulse

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  retailpulse:
    silver:
      +schema: silver
      +materialized: view
      +tags: ["silver"]
    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
